"""Add profile status to user model

Revision ID: 3ff793b0d809
Revises: 744be51ab9a1
Create Date: 2024-10-19 14:14:38.542072

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ff793b0d809'
down_revision = '744be51ab9a1'
branch_labels = None
depends_on = None


def upgrade():
    #
    profilestatus = postgresql.ENUM('active', 'inactive', name='profilestatus')
    profilestatus.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('profile_status', sa.Enum('active', 'inactive', name='profilestatus'), server_default='active',
                      nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_status')

    # ### end Alembic commands ###
