"""empty message

Revision ID: 744be51ab9a1
Revises: db8d0c6748c0
Create Date: 2024-10-13 18:14:26.707306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744be51ab9a1'
down_revision = 'db8d0c6748c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_photo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_photo_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True, server_default='No photo')

    # ### end Alembic commands ###
